<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.saltyfish</groupId>
        <artifactId>saltyfish-boot-server-archetype</artifactId>
        <version>1.0.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.saltyfish</groupId>
    <artifactId>saltyfish-boot-infrastructure</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>
    <name>saltyfish-boot-infrastructure</name>

    <dependencies>
        <dependency>
            <groupId>com.saltyfish</groupId>
            <artifactId>saltyfish-boot-domain</artifactId>
            <version>1.0.0</version>
        </dependency>

        <dependency>
            <groupId>com.saltyfish</groupId>
            <artifactId>saltyfish-boot-framework-dict</artifactId>
            <version>1.0.0</version>
        </dependency>

        <dependency>
            <groupId>com.saltyfish</groupId>
            <artifactId>saltyfish-boot-framework-data-permission</artifactId>
            <version>1.0.0</version>
        </dependency>

        <dependency>
            <groupId>com.saltyfish</groupId>
            <artifactId>saltyfish-boot-framework-tenant</artifactId>
            <version>1.0.0</version>
        </dependency>

        <dependency>
            <groupId>com.saltyfish</groupId>
            <artifactId>saltyfish-boot-framework-security</artifactId>
            <version>1.0.0</version>
        </dependency>

        <!-- Web 相关 -->
        <dependency>
            <groupId>com.saltyfish</groupId>
            <artifactId>saltyfish-boot-framework-mybatis</artifactId>
            <version>1.0.0</version>
        </dependency>

        <!-- DB 相关 -->
        <dependency>
            <groupId>com.saltyfish</groupId>
            <artifactId>saltyfish-boot-framework-redis</artifactId>
            <version>1.0.0</version>
        </dependency>

    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
    </build>
</project>
