<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.saltyfish</groupId>
        <artifactId>saltyfish-boot-server-archetype</artifactId>
        <version>1.0.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.saltyfish</groupId>
    <artifactId>saltyfish-boot-app</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>
    <name>saltyfish-boot-app</name>

    <dependencies>
        <dependency>
            <groupId>com.saltyfish</groupId>
            <artifactId>saltyfish-boot-infrastructure</artifactId>
            <version>1.0.0</version>
        </dependency>

        <dependency>
            <groupId>com.saltyfish</groupId>
            <artifactId>saltyfish-boot-client</artifactId>
            <version>1.0.0</version>
        </dependency>

        <dependency>
            <groupId>com.saltyfish</groupId>
            <artifactId>saltyfish-boot-integration</artifactId>
            <version>1.0.0</version>
        </dependency>

        <!-- Job 定时任务相关 -->
        <dependency>
            <groupId>com.saltyfish</groupId>
            <artifactId>saltyfish-boot-framework-job</artifactId>
            <version>1.0.0</version>
        </dependency>

        <!-- 消息队列相关 -->
        <dependency>
            <groupId>com.saltyfish</groupId>
            <artifactId>saltyfish-boot-framework-mq</artifactId>
            <version>1.0.0</version>
        </dependency>

        <!-- 单元测试 -->
        <dependency>
            <groupId>com.saltyfish</groupId>
            <artifactId>saltyfish-boot-framework-test</artifactId>
            <version>1.0.0</version>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
    </build>
</project>
